### ISSUE TITLE
cannot send event from fs watcher: sending into a full channel

### ISSUE THREAD

**Issue by tcoopman** [watchexec/watchexec#489] opened 2023-01-27 09:36 UTC
When running watchexec with: `watchexec -e ex,exs,heex --stdin-quit "mix test --stale"` I get lots of errors like this:

```
[[Error (not fatal)]]
cannot send event from fs watcher: sending into a full channel
```
Also happens without `--stdin-quit`. I didn't have this issue a couple of weeks ago.

The watcher still seems to work, but it's really hard to use because the full output shows the above message many times.

- Watchexec's version: 1.21.0
- The OS you're using: Linux 6.1.6-arch1-3

**Comment by passcod** [comment] 2023-01-27 09:42
Hmm, that's an interesting one. Can you try installing an earlier version to see if this is a regression or environmental?

**Comment by tcoopman** [comment] 2023-01-27 09:59
just tested on 
- 1.20.5: happens as well.
- 1.18.12: happens as well

I was playing around with different commands, but now I cannot trigger it anymore at all. :confused: 
It happened everytime, and now it doesn't happen anymore.

Didn't change anything expect trying the older versions and then switching back to the current release.

**Comment by passcod** [comment] 2023-01-28 03:20
Well, as this seems to be environmental, I'm going to close it for the moment. I've also reviewed the logfile you sent and can't see anything obvious or wrong happening before/during/after the errors. Reopen/comment if it happens again!

I'll make a separate issue about cleaning up the error output in the case of many repeated messages.

**Closed** 2023-01-28 03:20 UTC
Labels: need repro

**Comment by alecthomas** [comment] 2023-07-19 00:58
FWIW I'm seeing this too. I'm running four commands via watchexec, and they all seem to spew out this error in a burst occasionally, then stop. Everything seems to work fine though, so 🤷‍♂️

This is on a M2 MacBook Air.

**Comment by ModProg** [comment] 2023-10-08 10:49
I have this issue (I think it's the same) While using the library.

I'm running a command via `tokio::process` in `on_action` because I want to do something after it finished.

My guess is that this error might be related to that command sometimes blocking for quite a while (it is `cargo doc` and sometimes blocks due to other cargo processes locking the target directory).

My `on_action`
https://github.com/ModProg/cargo-watchdoc/blob/e17c6d30bdd271ab5b546b13ab18e76eb951c3a3/src/main.rs#L121-L135

**Comment by passcod** [comment] 2023-10-08 11:58
@ModProg I strongly suggest you not do that. The documentation is not super clear about this, I'll make it more explicit, but (currently) the `on_action` blocks the core event loop, so that the handler is run in a strictly serial fashion. If you do anything costly in there you'll let events pile up and they'll overwhelm the internal queues.

**Comment by ModProg** [comment] 2023-10-08 12:41
> @ModProg I strongly suggest you not do that. The documentation is not super clear about this, I'll make it more explicit, but (currently) the `on_action` blocks the core event loop, so that the handler is run in a strictly serial fashion. If you do anything costly in there you'll let events pile up and they'll overwhelm the internal queues.

that might explain it. Would it be possible for `command` to take a closure? I just need a way to call `reloader.reload()` after `cargo doc` is done.

**Comment by passcod** [comment] 2023-10-09 00:15
You can call reload() from anywhere, so spawn a new tokio task and don't block the action handler.

**Comment by dzmitry-lahoda** [comment] 2024-08-07 20:46
It seems can be reproduced on huge repos with many many files. Unfortunately I am on proprietary repo.

**Comment by dzmitry-lahoda** [comment] 2025-04-06 20:53
```sh
watchexec --verbose --log-file=../log.log --print-events  "clear && cargo lcheck --package=engine"
```

[log.log](https://github.com/user-attachments/files/19623489/log.log)

Got error. 

Do not see anything in logs.

May you elaborate what else add to parameters to see deeper? Should I run with strace (so it will be very hard because it reproduced one half hour randomly).
