### ISSUE TITLE
Support running as PID 1

### ISSUE THREAD

**Issue by Marwes** [watchexec/watchexec#140] opened 2019-11-07 09:42 UTC
When running watchexec (really, cargo-watch) in a docker container I would like that the watchexec process shutsdown when I request that the docker container shutsdown.

Currently SIGTERM is handled and sent to the child process which shutsdown my program as expected, but after that nothing happens. What I would like is that `watchexec`, after seeing the child process shutdown also shutsdown itself.

**Comment by passcod** [comment] 2019-11-07 11:38
That sounds reasonable

**Comment by passcod** [comment] 2019-11-07 12:04
Actually I can't reproduce this. Sending SIGTERM to watchexec kills it (and the child). Can you provide more detail as to how and what you're running?

**Comment by Marwes** [comment] 2019-11-07 15:39
Right, forgot that detail. It only seems to happen when running it as the main process in docker (PID 1) which has some special behaviour around signals.

To reproduce


### Dockerfile
```
FROM rust:1.38

RUN cargo install watchexec

COPY test.sh ./
```

### test.sh
```
trap 'echo "Received SIGTERM" && exit 1' TERM
while true; do sleep 1; done
```

Build and run docker

```
docker build . -t test
docker run -it --rm --name test test watchexec --verbose 'sh ./test.sh'
```

With the container running `docker kill -s SIGTERM test` can be ran after which `watchexec` says that it received the signal.

Remove the watchexec invocation and run the bare `sh ./test.sh` to sanity check that the script exits on SIGTERM.

**Comment by passcod** [comment] 2019-11-11 05:36
(Sorry for taking so long, I am looking at this and haven't forgotten.)

**Comment by passcod** [comment] 2019-11-18 11:30
Tried fixing this for a few days but ran into issues and it's delaying release, so I'm shelving this for now. Not happy about it, but I have to get other stuff out of the door before coming back to it.

**Comment by LucasPickering** [comment] 2020-11-05 01:43
@passcod I'm still running into this issue, did you ever get a chance to do more debugging? Is there anything I can do to help with the debugging?

**Comment by passcod** [comment] 2020-11-05 01:54
Haven't done anything more since. Workaround is obviously to not run as PID 1 (not hard, just wrap it in a shell), but I haven't looked deeper at how the way signals work for PID 1 affects its handling in watchexec.

It's been a year and I've forgotten things (also I'm busy, november is basically the worst time as I do nanowrimo); if you want to help better repro it from scratch and look at the handling code in signal.rs.

**Comment by LucasPickering** [comment] 2020-11-05 22:44
ok thanks, I will use an init process in the mean time and I'll try to do some debugging next week

**Comment by passcod** [comment] 2021-08-04 14:45
Dropping a note for future visitors that for the specific case of Docker, running with [the `--init` flag](https://docs.docker.com/engine/reference/run/#specify-an-init-process) solves this without needing your own init/shell/wrapper. It would still be nice to properly support being PID1 at some point though.

**Comment by tgrondier** [comment] 2021-08-23 10:23
If you're using watchexec as a sidecar in a kubernetes pod, a workaround for that (but only if your scripts can handle ungraceful stops), a workaround is to add the following to your watchexec container Dockerfile:

```Dockerfile
STOPSIGNAL SIGKILL
```

**Comment by matu3ba** [comment] 2022-08-23 09:47
@Marwes pid 1 ignores most signaling to not "accidentially shutting down the system", because child processes may use pid 1 as process group to signal the other children.

Thus `SIGKILL` should be expected. Can you confirm that `SIGKILL` works? If yes, please close this issue.

**Comment by passcod** [comment] 2023-02-14 22:16
This will be in 1.21.1

**Closed** 2023-02-14 22:30 UTC
Labels: OS: Linux, improvement, has workaround
