### ISSUE TITLE
Request: Rerun by user input

### ISSUE THREAD

**Issue by shelbyd** [watchexec/watchexec#291] opened 2022-05-30 22:39 UTC
Often, successful runs of a command require changes to the system that aren't immediately visible in the current directory (such as installing a package).

It would be nice to be able to manually trigger a re-run of the current command. Currently, I do this by Ctrl-C the watchexec process and rerunning it. I'd prefer to be able to just input <space> or something similar.

Obviously not a critical feature, but would help my flow a bit. Thanks for the better implementation of something I had made for myself!

**Comment by passcod** [comment] 2022-05-30 22:40
Duplicate of #67, already slated for 2.0.

**Closed by passcod** 2022-05-30 22:40 UTC

**Comment by ravicious** [comment] 2024-10-24 10:34
@passcod Did it get into v2? I'm reading the changelog but I don't see it mentioned.

**Comment by passcod** [comment] 2024-10-24 11:43
No, it's a duplicate. See #67
