### ISSUE TITLE
Upon file change detection, watchexec is opening the file using the registered Windows handler for that file extension

### ISSUE THREAD

**Issue by blaster151** [watchexec/watchexec#80] opened 2018-03-29 16:05 UTC
Can this behavior be prevented?

**Comment by mattgreen** [comment] 2018-04-25 12:42
I can't think of anything that would cause this. Can you provide a minimal working example?

**Comment by passcod** [comment] 2019-01-26 04:06
Closing for lack of repro.

**Comment by thisKai** [comment] 2019-12-06 13:11
I had the same problem, if I tell watchexec to run a powershell file
```powershell
watchexec -w .\folder .\script.ps1
```
It opens the script in VS Code, but if I explicitly start powershell, it does execute the script 
```powershell
watchexec -w .\folder 'powershell .\script.ps1'
```

**Comment by passcod** [comment] 2019-12-06 13:43
Well that's kinda horrifying

**Comment by mattgreen** [comment] 2019-12-06 15:59
Thanks for the example, @thisKai. Can you try replicating it by running `cmd.exe /C .\script.ps1`? It should produce the same behavior.

I think the issue is we always use `cmd.exe` to invoke shell commands. Perhaps we need to see if PowerShell is in use and use that instead.

**Comment by sergeevabc** [comment] 2021-04-06 20:08
Aggrrhh. How do I simply copy new files in the monitored folder to somewhere else?

**Comment by passcod** [comment] 2021-04-06 21:27
Hi @sergeevabc! Can you confirm (so we can finally start debugging this):
- that you're seeing the same issue, and that's why you're commenting here?
- that running the command @mattgreen provided above exhibits the behaviour?

There's no particular "simple" solution to what you're asking, though a script that looks at the `WATCHEXEC_` env vars we set and copies files will be the way, and I'm sure as a temporary workaround the above-mentioned will run your script:

```
watchexec -w .\folder 'powershell .\script.ps1'
```

**Comment by sergeevabc** [comment] 2021-04-06 21:35
@passcod, I had an outbreak earlier, because all the relevant tools from 10 pages of search results claim to be simple (`watchexec` included). Yyet the simplest task of monitoring some folder and copying changes to another folder turned out to be a hard one. In the end, after a lot of errors and irrelevant output I got the following (consider including something like this in examples section):
```
watchexec -d 1 -w c:\folder-to-monitor\ cp -r c:\folder-to-monitor\ d:\copy-changes-here\
```

**Comment by passcod** [comment] 2021-04-06 21:44
the "copying changes" part is the "not simple" part, which we don't claim to be simple about (or anything about, really). It's not a common request! That said, you seem to have found a good solution for yourself in a fairly simple package, so I'm glad it's working out for you.

**Comment by passcod** [comment] 2021-04-06 21:57
----

(unrelated to above convo with Aleksandr)

----

We've finally got some explanation for this bug! From twitter:

> [this is] expected behavior, since PowerShell scripts are not interpreted by cmd
>
> https://twitter.com/TronicJohn/status/1379552489826095107

A tad annoying, but something that can have a solution!

**Comment by passcod** [comment] 2021-04-06 22:08
The solution seems to be to switch the default windows interpreter to PowerShell, and have a little detection going on to see if what's being executed is a `.bat` (plus probably a cli switch for override) and run it in cmd instead.

However, that smells like a breaking change to me. We could:
- do the inverse as a temporary measure, set a `--powershell` flag to run in powershell, and then switch the behaviour around in a next breaking release.
- or do a breaking change: powershell is the present and the future of shells on windows, I think, and cmd is legacy at this point.

What do you think @mattgreen?

**Comment by passcod** [comment] 2021-04-10 18:15
There is now a new option, `--shell`, to select the shell to run the command, and `--shell=powershell` will effectively solve this issue. Idea is to switch the default to powershell in a future version (tentatively dubbed v2.0), at which point this issue will get closed.

**Comment by sergeevabc** [comment] 2021-04-10 18:28
@passcod, running Powershell on my Windows 7 is [too slow][1] to use it daily, it takes ~7 seconds to launch.

[1]: https://www.google.com/search?q=powershell+slow

**Comment by passcod** [comment] 2021-04-10 18:29
Well, there's time to reconsider. v2.0 won't be anytime soon.

**Comment by passcod** [comment] 2022-01-26 01:30
Default _will_ change at 2.0.

**Comment by passcod** [comment] 2024-04-20 13:30
Default has now changed, but a bit more cleverly than I suggested here:
- if the `SHELL` environment variable is set, we use that
- if we detect we're running under pwsh, we default to pwsh
- if we detect we're running under powershell, we default to powershell
- otherwise we fallback to cmd

**Closed by passcod** 2024-04-20 13:30 UTC
Labels: OS: Windows, improvement, has workaround
